name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.2'  # Set your Go version

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o chess-game-v2.exe

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v2
        with:
          name: chess-game-v2-windows
          path: chess-game-v2.exe
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./artifacts

      - name: Set release version
        id: vars
        run: echo "RELEASE_VERSION=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/chess-game-v2.exe
          asset_name: chess-game-v2.exe
          asset_content_type: application/octet-stream
